# Generated by Django 2.2.5 on 2019-09-27 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0002_institution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('address', models.CharField(max_length=128)),
                ('phone_number', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=12)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_comment', models.CharField(blank=True, max_length=256, null=True)),
                ('categories', models.ManyToManyField(related_name='donations', to='donation.Category')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='donation.Institution')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
